import React from 'react';

const Placeholder = ({ w, h }) => {
  return (
    <img
      className="profile"
      src={`data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAJQApgMBIgACEQEDEQH/xAAbAAACAgMBAAAAAAAAAAAAAAAABgQFAQMHAv/EADwQAAIBAwMCAwUGBAUEAwAAAAECAwAEEQUSITFBBhNRFCJhcYEyQpGhscEjUtHwBxUk4fEzgpLCFlNy/8QAGQEAAwEBAQAAAAAAAAAAAAAAAAMEAgEF/8QAIhEAAgICAgIDAQEAAAAAAAAAAAECEQMhEjEiQQQyURNx/9oADAMBAAIRAxEAPwDldFFFekYCiiigAqbpMPnXa8Z2kEemc8VCxnjNMnhSySacM0h3BgH2nHu965J0gQ9aDbkyWStukhC5bd1kbvk9/Wm4OWd0Z9gxn0BFUb/w57VYEVY4U2RonGMcZ/3qXDePds6IqKF++cnmvMybLMa0WeyM7mVRtC8VDJiTcz7ctxWiSK5uBlJHVR1Lt+2Men4ViK3t9rG5vBMy8Nl84paQ5HqQiVVKbXT4HnFe7aDyXwzBVPUHvUi2jtFztIUgZB3c4+WahapBZSSAT3ITvguoNdTAlzXlta2wOcqnHNerbU7OZPMBUSKNrEjGDS++mrMmLK7AUg4VzuU/+P7VW2+kajbXBMt3EI5D9j3sk9jzxWlBfpljw/kalbSQykNuU4BPftXLr60kaznSeRnQO0L5+6Ox+XX8KY4mn05MG4aObJ2qR1X0z/zVHfIPZrqSSc+csmMNwGBwf7+VU4VxdE2VHPWBVmU9VOKxW+8XbcPx1Oa0VYICiiigAooooAKKKKAC`}
      alt="no image"
    />
  );
};

export default Placeholder

